DROP DATABASE IF EXISTS SEGURADORA;
CREATE DATABASE SEGURADORA;
USE SEGURADORA;

CREATE TABLE endereco (
  ID int NOT NULL AUTO_INCREMENT,
  NUMERO int DEFAULT NULL,
  CEP char(8) DEFAULT NULL,
  RUA varchar(100) DEFAULT NULL,
  BAIRRO varchar(100) DEFAULT NULL,
  CIDADE varchar(100) DEFAULT NULL,
  ESTADO char(2) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE veiculo (
  ID int NOT NULL AUTO_INCREMENT,
  MARCA varchar(100) DEFAULT NULL,
  ANO_MODELO int DEFAULT NULL,
  PLACA_VEICULO char(8) DEFAULT NULL,
  COMBUSTIVEL varchar(30) DEFAULT NULL,
  VALOR double DEFAULT NULL,
  MODELO varchar(50) DEFAULT NULL,
  id_cliente int DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY PLACA_VEICULO (PLACA_VEICULO),
  KEY veiculo_cliente_fk (id_cliente),
  CONSTRAINT veiculo_cliente_fk FOREIGN KEY (id_cliente) REFERENCES cliente (ID)
);
 
CREATE TABLE cliente (
  ID int NOT NULL AUTO_INCREMENT,
  NOME varchar(255) DEFAULT NULL,
  CPF char(11) DEFAULT NULL,
  DATA_NASCIMENTO datetime DEFAULT NULL,
  TELEFONE char(11) DEFAULT NULL,
  ID_ENDERECO int NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID (ID),
  UNIQUE KEY CPF (CPF),
  KEY ID_ENDERECO (ID_ENDERECO),
  CONSTRAINT cliente_ibfk_1 FOREIGN KEY (ID_ENDERECO) REFERENCES endereco (ID)
);
 
CREATE TABLE seguro (
  ID int NOT NULL AUTO_INCREMENT,
  ID_CLIENTE int DEFAULT NULL,
  ID_VEICULO int DEFAULT NULL,
  NUMERO_PROPOSTA varchar(8) DEFAULT NULL,
  DATA_INICIO_VIGENCIA datetime DEFAULT NULL,
  DATA_FIM_VIGENCIA datetime DEFAULT NULL,
  RCF_DANOS_MATERIAIS double DEFAULT NULL,
  RCF_DANOS_CORPORAIS double DEFAULT NULL,
  FRANQUIA varchar(50) DEFAULT NULL,
  ASSISTENCIA varchar(100) DEFAULT NULL,
  CARRO_RESERVA varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY IDCLIENTE (ID_CLIENTE),
  KEY IDVEICULO (ID_VEICULO),
  CONSTRAINT seguro_ibfk_1 FOREIGN KEY (ID_CLIENTE) REFERENCES cliente (ID),
  CONSTRAINT seguro_ibfk_2 FOREIGN KEY (ID_VEICULO) REFERENCES veiculo (ID)
);
 
CREATE TABLE sinistro (
  ID int NOT NULL AUTO_INCREMENT,
  NUMERO_SINISTRO varchar(10) DEFAULT NULL,
  TIPO_SINISTRO varchar(50) DEFAULT NULL,
  ID_SEGURO int DEFAULT NULL,
  DATA_SINISTRO datetime DEFAULT NULL,
  VALOR_FRANQUIA double DEFAULT NULL,
  VALOR_ORCADO double DEFAULT NULL,
  VALOR_PAGO double DEFAULT NULL,
  SITUACAO varchar(255) DEFAULT NULL,
  MOTIVO varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY ID_SEGURO (ID_SEGURO),
  CONSTRAINT sinistro_ibfk_1 FOREIGN KEY (ID_SEGURO) REFERENCES seguro (ID)
);
